### ISSUE TITLE
The edit link is broken

### ISSUE THREAD

**Issue by hsluoyz** [casnode/casnode-website#12]
See: https://casnode.org/docs/

![image](https://user-images.githubusercontent.com/3787410/123378926-f3c25080-d5bf-11eb-911c-e8467182b291.png)

![image](https://user-images.githubusercontent.com/3787410/123378938-f6bd4100-d5bf-11eb-971c-d30ab2cca160.png)

**Comment by hsluoyz** [comment]
@oranges-eating @ErikQQY @turbodog03

**Comment by turbodog03** [comment]
> @oranges-eating @ErikQQY @turbodog03

fix it soon
