### ISSUE TITLE
Github action fail

### ISSUE THREAD

**Issue by ErikQQY** [casnode/casnode-website#8]
The action log shows that there is something wrong with Korean translation, and the error prevent the auto-publish of casnode-website.

![korean](https://user-images.githubusercontent.com/52615090/122193436-13be8980-cec7-11eb-8199-98e3647eed73.png)

**Comment by hsluoyz** [comment]
@ErikQQY why?

**Comment by ErikQQY** [comment]
The configuration is same as the configuration of casdoor-website. And there are no errors with other translations.
